const PROGRESS_API='https://uxkmgwofnewrdcixjpku.supabase.co/functions/v1/tender-state';
const STORAGE_KEY='tenderRadarWorkspaceKey';
const state={tenders:[],status:null,progress:{},workspaceKey:'',progressUnlocked:false};
const els=Object.fromEntries(['lastUpdated','sourceHealth','totalCount','highCount','closingCount','sourceCount','search','source','relevance','progressFilter','sort','visibleCount','tenderList','emptyState','refreshBtn','progressTitle','progressMessage','workspaceKey','unlockBtn','lockBtn'].map(id=>[id,document.getElementById(id)]));
const noteTimers=new Map();
const esc=(v='')=>String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const encodeKey=v=>encodeURIComponent(String(v||''));
const decodeKey=v=>decodeURIComponent(v||'');
function fmtDate(v){if(!v)return'Not stated';const d=new Date(v);if(Number.isNaN(d.getTime()))return'Not stated';return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}
function fmtValue(value,currency){if(value===null||value===undefined||Number.isNaN(Number(value)))return'Not stated';const cur=currency||'GBP';try{return new Intl.NumberFormat('en-GB',{style:'currency',currency:cur,maximumFractionDigits:0}).format(Number(value))}catch{return`${Number(value).toLocaleString('en-GB')} ${cur}`}}
function daysUntil(v){if(!v)return null;return Math.ceil((new Date(v).getTime()-Date.now())/86400000)}
function deadlineLabel(v){const days=daysUntil(v);if(days===null)return'Deadline not stated';if(days<0)return'Closed';if(days===0)return'Closes today';if(days===1)return'1 day left';return`${days} days left`}
function scoreClass(score){return score>=60?'high':'mid'}
function progressFor(key){return state.progress[key]||{submitted:false,note:'',submitted_at:null,updated_at:null}}
function setProgressMessage(message,isError=false){els.progressMessage.textContent=message;els.progressMessage.classList.toggle('error',isError)}
function renderWorkspace(){els.workspaceKey.hidden=state.progressUnlocked;els.unlockBtn.hidden=state.progressUnlocked;els.lockBtn.hidden=!state.progressUnlocked;els.progressTitle.textContent=state.progressUnlocked?'Progress unlocked':'Progress locked';if(state.progressUnlocked){const submitted=Object.values(state.progress).filter(x=>x.submitted).length;setProgressMessage(`${submitted} tender${submitted===1?'':'s'} marked submitted. Notes save automatically.`)}else{setProgressMessage('Unlock once to save submitted status and notes across refreshes.')}}
function renderSources(){const current=els.source.value;const sources=[...new Set(state.tenders.map(x=>x.source).filter(Boolean))].sort();els.source.innerHTML='<option value="all">All sources</option>'+sources.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');if(sources.includes(current))els.source.value=current}
function filtered(){const q=els.search.value.trim().toLowerCase();const source=els.source.value;const minRel=Number(els.relevance.value||12);const progressFilter=els.progressFilter.value;let rows=state.tenders.filter(t=>{const hay=`${t.title||''} ${t.buyer||''} ${t.description||''} ${(t.matched||[]).join(' ')} ${(t.cpv||[]).join(' ')}`.toLowerCase();const submitted=!!progressFor(t.key).submitted;const progressOk=progressFilter==='all'||(progressFilter==='submitted'&&submitted)||(progressFilter==='not-submitted'&&!submitted);return(!q||hay.includes(q))&&(source==='all'||t.source===source)&&Number(t.relevance||0)>=minRel&&progressOk});const sort=els.sort.value;rows.sort((a,b)=>{if(sort==='deadline')return(a.deadline||'9999').localeCompare(b.deadline||'9999');if(sort==='newest')return(b.published_at||'').localeCompare(a.published_at||'');if(sort==='value')return Number(b.value||0)-Number(a.value||0);return Number(b.relevance||0)-Number(a.relevance||0)||(a.deadline||'9999').localeCompare(b.deadline||'9999')});return rows}
function render(){const rows=filtered();els.visibleCount.textContent=rows.length.toLocaleString('en-GB');els.emptyState.hidden=rows.length!==0;els.tenderList.innerHTML=rows.map(t=>{const days=daysUntil(t.deadline);const urgent=days!==null&&days<=7;const desc=t.description?(t.description.length>420?`${t.description.slice(0,420)}…`:t.description):'No summary supplied.';const p=progressFor(t.key);const submitted=!!p.submitted;const disabled=state.progressUnlocked?'':'disabled';return`<article class="tender ${submitted?'is-submitted':''}" data-card-key="${encodeKey(t.key)}"><div><div class="badges"><span class="badge source">${esc(t.source)}</span><span class="badge score ${scoreClass(Number(t.relevance||0))}">${Number(t.relevance||0)}% fit</span><span class="badge">${esc(t.country||'')}</span>${submitted?'<span class="badge submitted-badge">Submitted</span>':''}</div><h2>${esc(t.title)}</h2><p class="buyer">${esc(t.buyer)}</p><p class="desc">${esc(desc)}</p><div class="meta"><span><strong>Published:</strong> ${esc(fmtDate(t.published_at))}</span><span><strong>Value:</strong> ${esc(fmtValue(t.value,t.currency))}</span>${t.cpv?.length?`<span><strong>CPV:</strong> ${esc(t.cpv.slice(0,3).join(', '))}</span>`:''}</div>${t.matched?.length?`<div class="matches">Matched: ${esc(t.matched.slice(0,8).join(' · '))}</div>`:''}<div class="tender-progress"><div class="progress-row"><button class="submit-toggle ${submitted?'submitted':''}" data-key="${encodeKey(t.key)}" type="button" ${disabled}>${submitted?'✓ Submitted':'Mark submitted'}</button><span class="save-state" data-save-key="${encodeKey(t.key)}">${state.progressUnlocked?(p.updated_at?'Saved':'Ready'):'Unlock workspace to save'}</span></div><textarea class="note-input" data-key="${encodeKey(t.key)}" rows="3" maxlength="5000" placeholder="Add a note for this tender…" ${disabled}>${esc(p.note||'')}</textarea></div></div><div class="side"><div class="deadline ${urgent?'urgent':''}">${esc(deadlineLabel(t.deadline))}<strong>${esc(fmtDate(t.deadline))}</strong></div><a class="open-link" href="${esc(t.url)}" target="_blank" rel="noopener noreferrer">Open tender ↗</a></div></article>`}).join('')}
function renderStats(){const active=state.tenders;els.totalCount.textContent=active.length.toLocaleString('en-GB');els.highCount.textContent=active.filter(t=>Number(t.relevance||0)>=60).length.toLocaleString('en-GB');els.closingCount.textContent=active.filter(t=>{const d=daysUntil(t.deadline);return d!==null&&d>=0&&d<=7}).length.toLocaleString('en-GB');els.sourceCount.textContent=new Set(active.map(t=>t.source)).size;if(state.status?.updated_at)els.lastUpdated.textContent=fmtDate(state.status.updated_at);else els.lastUpdated.textContent='Awaiting first refresh';const errors=state.status?.errors||[];els.sourceHealth.textContent=errors.length?`${errors.length} source warning${errors.length===1?'':'s'} — cached data remains visible`:'All configured sources refreshed successfully'}
async function progressRequest(payload,key=state.workspaceKey){const res=await fetch(PROGRESS_API,{method:'POST',headers:{'Content-Type':'application/json','x-workspace-key':key},body:JSON.stringify(payload)});let body={};try{body=await res.json()}catch{}if(!res.ok)throw new Error(body.error||`Progress service error ${res.status}`);return body}
async function unlockWorkspace(key,{silent=false}={}){const clean=String(key||'').trim();if(!clean)return false;try{if(!silent)setProgressMessage('Unlocking…');const body=await progressRequest({action:'list'},clean);state.workspaceKey=clean;state.progressUnlocked=true;state.progress=Object.fromEntries((body.items||[]).map(x=>[x.tender_key,x]));localStorage.setItem(STORAGE_KEY,clean);els.workspaceKey.value='';renderWorkspace();render();return true}catch(err){state.workspaceKey='';state.progressUnlocked=false;state.progress={};localStorage.removeItem(STORAGE_KEY);renderWorkspace();if(!silent)setProgressMessage(err.message==='Invalid workspace key'?'Workspace key not recognised.':`Could not unlock: ${err.message}`,true);render();return false}}
function lockWorkspace(){state.workspaceKey='';state.progressUnlocked=false;state.progress={};localStorage.removeItem(STORAGE_KEY);renderWorkspace();render()}
function tenderByKey(key){return state.tenders.find(t=>t.key===key)}
function saveLabel(key,text,isError=false){const el=els.tenderList.querySelector(`[data-save-key="${CSS.escape(encodeKey(key))}"]`);if(el){el.textContent=text;el.classList.toggle('error',isError)}}
async function saveProgress(key,patch,{rerender=false}={}){if(!state.progressUnlocked)return;const tender=tenderByKey(key);if(!tender)return;const current=progressFor(key);const next={...current,...patch};state.progress[key]=next;saveLabel(key,'Saving…');try{const body=await progressRequest({action:'save',tender_key:key,tender_title:tender.title||'',buyer:tender.buyer||'',source:tender.source||'',tender_url:tender.url||'',submitted:!!next.submitted,note:next.note||''});state.progress[key]=body.item||next;if(rerender)render();else saveLabel(key,'Saved');renderWorkspace()}catch(err){saveLabel(key,'Save failed',true)}}
async function loadData(){const nonce=Date.now();const[tendersRes,statusRes]=await Promise.all([fetch(`data/tenders.json?v=${nonce}`,{cache:'no-store'}),fetch(`data/status.json?v=${nonce}`,{cache:'no-store'})]);if(!tendersRes.ok)throw new Error('Tender data unavailable');state.tenders=await tendersRes.json();state.status=statusRes.ok?await statusRes.json():null;renderSources();renderStats();render()}
['search','source','relevance','progressFilter','sort'].forEach(id=>els[id].addEventListener('input',render));
els.refreshBtn.addEventListener('click',()=>loadData().catch(console.error));
els.unlockBtn.addEventListener('click',()=>unlockWorkspace(els.workspaceKey.value));
els.workspaceKey.addEventListener('keydown',e=>{if(e.key==='Enter')unlockWorkspace(els.workspaceKey.value)});
els.lockBtn.addEventListener('click',lockWorkspace);
els.tenderList.addEventListener('click',e=>{const btn=e.target.closest('.submit-toggle');if(!btn||!state.progressUnlocked)return;const key=decodeKey(btn.dataset.key);const current=progressFor(key);saveProgress(key,{submitted:!current.submitted},{rerender:true})});
els.tenderList.addEventListener('input',e=>{const input=e.target.closest('.note-input');if(!input||!state.progressUnlocked)return;const key=decodeKey(input.dataset.key);state.progress[key]={...progressFor(key),note:input.value};saveLabel(key,'Typing…');clearTimeout(noteTimers.get(key));noteTimers.set(key,setTimeout(()=>saveProgress(key,{note:input.value}),700))});
els.tenderList.addEventListener('focusout',e=>{const input=e.target.closest('.note-input');if(!input||!state.progressUnlocked)return;const key=decodeKey(input.dataset.key);clearTimeout(noteTimers.get(key));saveProgress(key,{note:input.value})});
renderWorkspace();
loadData().catch(err=>{els.lastUpdated.textContent='Data unavailable';els.sourceHealth.textContent=err.message});
const storedKey=localStorage.getItem(STORAGE_KEY);if(storedKey)unlockWorkspace(storedKey,{silent:true});
setInterval(()=>loadData().catch(console.error),120000);
