const state={tenders:[],status:null};
const els=Object.fromEntries(['lastUpdated','sourceHealth','totalCount','highCount','closingCount','sourceCount','search','source','relevance','sort','visibleCount','tenderList','emptyState','refreshBtn'].map(id=>[id,document.getElementById(id)]));
const esc=(v='')=>String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
function fmtDate(v){if(!v)return'Not stated';const d=new Date(v);if(Number.isNaN(d.getTime()))return'Not stated';return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}
function fmtValue(value,currency){if(value===null||value===undefined||Number.isNaN(Number(value)))return'Not stated';const cur=currency||'GBP';try{return new Intl.NumberFormat('en-GB',{style:'currency',currency:cur,maximumFractionDigits:0}).format(Number(value))}catch{return`${Number(value).toLocaleString('en-GB')} ${cur}`}}
function daysUntil(v){if(!v)return null;return Math.ceil((new Date(v).getTime()-Date.now())/86400000)}
function deadlineLabel(v){const days=daysUntil(v);if(days===null)return'Deadline not stated';if(days<0)return'Closed';if(days===0)return'Closes today';if(days===1)return'1 day left';return`${days} days left`}
function scoreClass(score){return score>=60?'high':'mid'}
function renderSources(){const current=els.source.value;const sources=[...new Set(state.tenders.map(x=>x.source).filter(Boolean))].sort();els.source.innerHTML='<option value="all">All sources</option>'+sources.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');if(sources.includes(current))els.source.value=current}
function filtered(){const q=els.search.value.trim().toLowerCase();const source=els.source.value;const minRel=Number(els.relevance.value||12);let rows=state.tenders.filter(t=>{const hay=`${t.title||''} ${t.buyer||''} ${t.description||''} ${(t.matched||[]).join(' ')} ${(t.cpv||[]).join(' ')}`.toLowerCase();return(!q||hay.includes(q))&&(source==='all'||t.source===source)&&Number(t.relevance||0)>=minRel});const sort=els.sort.value;rows.sort((a,b)=>{if(sort==='deadline')return(a.deadline||'9999').localeCompare(b.deadline||'9999');if(sort==='newest')return(b.published_at||'').localeCompare(a.published_at||'');if(sort==='value')return Number(b.value||0)-Number(a.value||0);return Number(b.relevance||0)-Number(a.relevance||0)||(a.deadline||'9999').localeCompare(b.deadline||'9999')});return rows}
function render(){const rows=filtered();els.visibleCount.textContent=rows.length.toLocaleString('en-GB');els.emptyState.hidden=rows.length!==0;els.tenderList.innerHTML=rows.map(t=>{const days=daysUntil(t.deadline);const urgent=days!==null&&days<=7;const desc=t.description?(t.description.length>420?`${t.description.slice(0,420)}…`:t.description):'No summary supplied.';return`<article class="tender"><div><div class="badges"><span class="badge source">${esc(t.source)}</span><span class="badge score ${scoreClass(Number(t.relevance||0))}">${Number(t.relevance||0)}% fit</span><span class="badge">${esc(t.country||'')}</span></div><h2>${esc(t.title)}</h2><p class="buyer">${esc(t.buyer)}</p><p class="desc">${esc(desc)}</p><div class="meta"><span><strong>Published:</strong> ${esc(fmtDate(t.published_at))}</span><span><strong>Value:</strong> ${esc(fmtValue(t.value,t.currency))}</span>${t.cpv?.length?`<span><strong>CPV:</strong> ${esc(t.cpv.slice(0,3).join(', '))}</span>`:''}</div>${t.matched?.length?`<div class="matches">Matched: ${esc(t.matched.slice(0,8).join(' · '))}</div>`:''}</div><div class="side"><div class="deadline ${urgent?'urgent':''}">${esc(deadlineLabel(t.deadline))}<strong>${esc(fmtDate(t.deadline))}</strong></div><a class="open-link" href="${esc(t.url)}" target="_blank" rel="noopener noreferrer">Open tender ↗</a></div></article>`}).join('')}
function renderStats(){const active=state.tenders;els.totalCount.textContent=active.length.toLocaleString('en-GB');els.highCount.textContent=active.filter(t=>Number(t.relevance||0)>=60).length.toLocaleString('en-GB');els.closingCount.textContent=active.filter(t=>{const d=daysUntil(t.deadline);return d!==null&&d>=0&&d<=7}).length.toLocaleString('en-GB');els.sourceCount.textContent=new Set(active.map(t=>t.source)).size;if(state.status?.updated_at)els.lastUpdated.textContent=fmtDate(state.status.updated_at);else els.lastUpdated.textContent='Awaiting first refresh';const errors=state.status?.errors||[];els.sourceHealth.textContent=errors.length?`${errors.length} source warning${errors.length===1?'':'s'} — cached data remains visible`:'All configured sources refreshed successfully'}
async function loadData(){const nonce=Date.now();const[tendersRes,statusRes]=await Promise.all([fetch(`data/tenders.json?v=${nonce}`,{cache:'no-store'}),fetch(`data/status.json?v=${nonce}`,{cache:'no-store'})]);if(!tendersRes.ok)throw new Error('Tender data unavailable');state.tenders=await tendersRes.json();state.status=statusRes.ok?await statusRes.json():null;renderSources();renderStats();render()}
['search','source','relevance','sort'].forEach(id=>els[id].addEventListener('input',render));els.refreshBtn.addEventListener('click',()=>loadData().catch(console.error));
loadData().catch(err=>{els.lastUpdated.textContent='Data unavailable';els.sourceHealth.textContent=err.message});setInterval(()=>loadData().catch(console.error),120000);
